// apps/test-react/src/App.tsx
import { useState } from "react";

import { LmPrototypeStencilButton, LmPrototypeStencilIcon,} from "@lm-prototype-stencil/components-react";

import "@lm-prototype-stencil/tokens/dist/themes/light.css";
import "@lm-prototype-stencil/tokens/dist/themes/dark.css";

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => (
    <section style={{ marginBottom: 32 }}>
        <h2 style={{
            fontSize: 14,
            fontWeight: 600,
            textTransform: "uppercase",
            letterSpacing: "0.05em",
            marginBottom: 12,
            color: "var(--lm-prototype-color-text-secondary)",
        }}
        >
            {title}
        </h2>
        <div style={{ display: "flex", gap: 12, flexWrap: "wrap", alignItems: "center" }}>
            {children}
        </div>
    </section>
);

export default function App() {
    const [darkMode, setDarkMode] = useState(false);
    const [loading, setLoading] = useState(false);

    const toggleTheme = () => {
        const next = !darkMode;
        setDarkMode(next);
        document.documentElement.dataset["theme"] = next ? "dark" : "";
    };

    const simulateAsync = () => {
        setLoading(true);
        setTimeout(() => setLoading(false), 2000);
    };

    return (
        <div style={{
            padding: 40,
            minHeight: "100vh",
            background: "var(--lm-prototype-color-surface-default)",
            color: "var(--lm-prototype-color-text-primary)",
            fontFamily: "system-ui, sans-serif",
        }}
        >
            <header style={{
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
                marginBottom: 40,
                borderBottom: "1px solid var(--lm-prototype-color-border-default)",
                paddingBottom: 20,
            }}
            >
                <h1 style={{ fontSize: 24, fontWeight: 700, margin: 0 }}>
                    Design System with Stencil — React Test App
                </h1>
                <LmPrototypeStencilButton variant="tertiary" onClick={toggleTheme}>
                    {darkMode ? "☀️ Light" : "🌙 Dark"}
                </LmPrototypeStencilButton>
            </header>

            <Section title="Variants">
                <LmPrototypeStencilButton variant="primary">Primary</LmPrototypeStencilButton>
                <LmPrototypeStencilButton variant="secondary">Secondary</LmPrototypeStencilButton>
                <LmPrototypeStencilButton variant="tertiary">Tertiary</LmPrototypeStencilButton>
                <LmPrototypeStencilButton variant="danger">Danger</LmPrototypeStencilButton>
            </Section>

            <Section title="Sizes">
                <LmPrototypeStencilButton size="sm">Small</LmPrototypeStencilButton>
                <LmPrototypeStencilButton size="md">Medium</LmPrototypeStencilButton>
                <LmPrototypeStencilButton size="lg">Large</LmPrototypeStencilButton>
            </Section>

            <Section title="With Icons">
                <LmPrototypeStencilButton variant="primary">
                    <LmPrototypeStencilIcon slot="start" name="arrow-right" />
                    Continue
                </LmPrototypeStencilButton>
                <LmPrototypeStencilButton variant="secondary">
                    Save
                    <LmPrototypeStencilIcon slot="end" name="check" />
                </LmPrototypeStencilButton>
                <LmPrototypeStencilButton variant="danger">
                    <LmPrototypeStencilIcon slot="start" name="x" />
                    Remove
                </LmPrototypeStencilButton>
            </Section>

            <Section title="States">
                <LmPrototypeStencilButton loading={loading} onClick={simulateAsync}>
                    {loading ? "Saving…" : "Click to load (2s)"}
                </LmPrototypeStencilButton>
                <LmPrototypeStencilButton disabled>Disabled</LmPrototypeStencilButton>
                <LmPrototypeStencilButton loading>Always loading</LmPrototypeStencilButton>
            </Section>

            <Section title="Form Participation">
                <form
                    onSubmit={(e) => {
                        e.preventDefault();
                        alert("Submitted!");
                    }}
                    style={{ display: "flex", gap: 8, alignItems: "center" }}
                >
                    <input
                        name="q"
                        placeholder="Type something…"
                        style={{
                            padding: "8px 12px",
                            border: "1px solid var(--lm-prototype-color-border-default)",
                            borderRadius: "var(--lm-prototype-radius-md)",
                            background: "var(--lm-prototype-color-surface-raised)",
                            color: "var(--lm-prototype-color-text-primary)",
                            fontSize: "14px",
                        }}
                    />
                    <LmPrototypeStencilButton type="submit">Submit</LmPrototypeStencilButton>
                </form>
            </Section>
        </div>
    );
}

// apps/test-angular/src/app/app.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';

import { LmPrototypeStencilButton, LmPrototypeStencilIcon } from '@lm-prototype-stencil/components-angular';

interface ButtonDemo {
  variant: 'primary' | 'secondary' | 'tertiary' | 'danger';
  label: string;
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, LmPrototypeStencilButton, LmPrototypeStencilIcon],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <div class="app">
      <header class="app-header">
        <h1>Design System — Angular Test App</h1>
        <lm-prototype-stencil-button variant="tertiary" (click)="toggleTheme()">
          {{ darkMode ? '☀️ Light' : '🌙 Dark' }}
        </lm-prototype-stencil-button>
      </header>

      <main class="app-main">
        <section class="demo-section">
          <h2 class="demo-title">Variants</h2>
          <div class="demo-row">
            <lm-prototype-stencil-button variant="primary">Primary</lm-prototype-stencil-button>
            <lm-prototype-stencil-button variant="secondary">Secondary</lm-prototype-stencil-button>
            <lm-prototype-stencil-button variant="tertiary">Tertiary</lm-prototype-stencil-button>
            <lm-prototype-stencil-button variant="danger">Danger</lm-prototype-stencil-button>
          </div>
        </section>

        <section class="demo-section">
          <h2 class="demo-title">Sizes</h2>
          <div class="demo-row">
            <lm-prototype-stencil-button size="sm">Small</lm-prototype-stencil-button>
            <lm-prototype-stencil-button size="md">Medium</lm-prototype-stencil-button>
            <lm-prototype-stencil-button size="lg">Large</lm-prototype-stencil-button>
          </div>
        </section>

        <section class="demo-section">
          <h2 class="demo-title">With Icons</h2>
          <div class="demo-row">
            <lm-prototype-stencil-button variant="primary">
              <lm-prototype-stencil-icon slot="start" name="arrow-right"></lm-prototype-stencil-icon>
              Continue
            </lm-prototype-stencil-button>
            <lm-prototype-stencil-button variant="secondary">
              Save
              <lm-prototype-stencil-icon slot="end" name="check"></lm-prototype-stencil-icon>
            </lm-prototype-stencil-button>
            <lm-prototype-stencil-button variant="danger">
              <lm-prototype-stencil-icon slot="start" name="x"></lm-prototype-stencil-icon>
              Remove
            </lm-prototype-stencil-button>
          </div>
        </section>

        <section class="demo-section">
          <h2 class="demo-title">States</h2>
          <div class="demo-row">
            <lm-prototype-stencil-button [loading]="loading" (click)="simulateAsync()">
              {{ loading ? 'Saving…' : 'Click to load (2s)' }}
            </lm-prototype-stencil-button>
            <lm-prototype-stencil-button disabled>Disabled</lm-prototype-stencil-button>
            <lm-prototype-stencil-button loading>Always loading</lm-prototype-stencil-button>
          </div>
        </section>

        <section class="demo-section">
          <h2 class="demo-title">Form Participation</h2>
          <form (submit)="onSubmit($event)" class="demo-form">
            <input
              name="q"
              placeholder="Type something…"
              class="demo-input"
            />
            <lm-prototype-stencil-button type="submit">Submit</lm-prototype-stencil-button>
            <lm-prototype-stencil-button type="reset" variant="tertiary">Reset</lm-prototype-stencil-button>
          </form>
        </section>

      </main>
    </div>
  `,
  styles: [`
    /* Dina stilar är perfekta, behåller dem precis som de är! */
    .app {
      padding: 40px;
      min-height: 100vh;
    }

    .app-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 40px;
      padding-bottom: 20px;
      border-bottom: 1px solid var(--lm-prototype-stencil-color-border-default);
    }

    h1 {
      font-size: 24px;
      font-weight: 700;
      margin: 0;
    }

    .demo-section {
      margin-bottom: 32px;
    }

    .demo-title {
      font-size: 12px;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      color: var(--lm-prototype-stencil-color-text-secondary);
      margin: 0 0 12px;
    }

    .demo-row {
      display: flex;
      gap: 12px;
      flex-wrap: wrap;
      align-items: center;
    }

    .demo-form {
      display: flex;
      gap: 8px;
      align-items: center;
    }

    .demo-input {
      padding: 8px 12px;
      border: 1px solid var(--lm-prototype-stencil-color-border-default);
      border-radius: var(--lm-prototype-stencil-radius-md);
      background: var(--lm-prototype-stencil-color-surface-raised);
      color: var(--lm-prototype-stencil-color-text-primary);
      font-size: var(--lm-prototype-stencil-font-size-md);
      font-family: inherit;
    }

    .demo-input:focus {
      outline: 2px solid var(--lm-prototype-stencil-color-border-focus);
      outline-offset: 2px;
    }
  `],
})
export class AppComponent {
  darkMode = false;
  loading = false;

  toggleTheme(): void {
    this.darkMode = !this.darkMode;
    document.documentElement.dataset['theme'] = this.darkMode ? 'dark' : '';
  }

  simulateAsync(): void {
    this.loading = true;
    setTimeout(() => { this.loading = false; }, 2000);
  }

  onSubmit(event: Event): void {
    event.preventDefault();
    const data = new FormData(event.target as HTMLFormElement);
    alert('Submitted: ' + JSON.stringify(Object.fromEntries(data as any)));
  }
}
